task = "compression"
pipeline = false
task_data_dir = "./test_data/test"

feature_index_path = "./test_data/default.index"
dedup_index_path = "./test_data/default.dedup"
chunk_data_path = "./test_data/default.data"
chunk_meta_path = "./test_data/default.meta"
file_meta_path = "./test_data/default.file"

[feature]
type = "palantir"

[chunker]
# one of fast-cdc, rabin-cdc
type = "fast-cdc"
min_chunk_size = 8192 # 8kb
max_chunk_size = 8192
stop_mask = 8191 # 1 << 13 - 1, only for fast cdc

[storage]
encoder = "xdelta"
cache_size = 500 #mb